### PR TITLE
Added Landmark_model_test

### LINKED ISSUE #46: [Tests]: Write Test for beacon project.
The following architecture needs to be followed while writing tests: 
- model_tests
- service_tests
- widget_tests
- viewmodel_tests 

- [ ]  Login Screen
- [ ] Home page
- [ ] beacon_card.dart
- [ ] create_join_dialog.dart
- [ ] dialog_boxes.dart
- [ ] hike_button.dart
- [ ] hike_screen_widget.dart
- [ ] shape_painter.dart

For the Hike screen, MVVM architecture isn't followed so I am creating an issue for refactoring it, once it's done then tests can be added for that screen too.

Feel free to add/suggest anything that you think is missing.

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
Partly fixes #46 

Describe the changes you have made in this PR - Added test for landmark model

### CODE REVIEW

**Comment by Aadeesh11** [comment]
Both LandMark and Location fromJson method is being automatically being tested in Beacon fromJson test. This can add redundancy. 😅

**Comment by ItsAdityaKSingh** [comment]
Yes, but as there are separate models for it, having particular tests could increase code coverage and test each of them particularly too.

**Comment by nb9960** [comment]
> There shouldn't be a redundancy as there are separate models for fetching it; having particular tests could increase code coverage and test each of them particularly too.

But each field is already tested there too. I'd agreed to your statement if there would've other use cases for this model.
To reduce the redundancy what we can do is to just add validations here and PR #114 should use these. In any case, it would be better if you both collaborate and decide to go with one flow.

**Comment by ItsAdityaKSingh** [comment]
Sure @nb9960! I'll do the needful

**Comment by ItsAdityaKSingh** [comment]
Not necessary as PR #114 already handles it.

**Pull request closed without merging**
