### PR TITLE
Issue #110 and #163 solved (AlterDialog UI fixes and made loading screen) 

### PR DESCRIPTION
**Pull request by codewithkushagra**
#110 and #163  

I have made the Alertdialog box edges round, for logout pop up

WhatsApp Image 2022-04-16 at 7 47 02 PM 
WhatsApp Image 2022-04-16 at 7 47 31 PM

Consistent login screen added everywhere with image from assets and the loading animation

https://user-images.githubusercontent.com/72088481/163722180-0c661c48-8e2c-460b-b208-9a223614d62f.mp4

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

**Comment by codewithkushagra** [comment]
I have added a loading screen which is consistent and also corrected the logout pop up round property, please review my PR

**Comment by nb9960** [comment]
You've pushed all the previous commits, which obviously isn't a good practice. Please only push the changes you've made to the existing codebase.

**Comment by codewithkushagra** [comment]
Is this okay can you review it once again @nb9960

**Comment by codewithkushagra** [comment]
> You've pushed all the previous commits, which obviously isn't a good practice. Please only push the changes you've made to the existing codebase.

Please review the PR once, is this right

**Comment by ItsAdityaKSingh** [comment]
LGTM. Could you review it @nb9960?

**Pull request merged**
