### PR TITLE
fix: fixed the keyboard stays open bug.

### LINKED ISSUE #27: [Auth Screen] Bug: If keyboard is open and we switch tabs, keyboard stays open and input is connected to prev tab.
Here is a screen recording of the issue: (which also happens while manually swiping across screen to change tabs)

https://user-images.githubusercontent.com/66922161/147469173-3f4c407f-2833-4e93-98de-ccd90243159f.mp4

How it can be: 

https://user-images.githubusercontent.com/66922161/147470999-9fe82d8d-e712-427c-8eec-b8e8b0746adb.mp4

### PR DESCRIPTION
**Pull request by Aadeesh11**
Fixes #27, #44.

Expected behaviour is described in the issue itself.
Also (not in the screenRecording) only those textfields that are visible will validate.

### CODE REVIEW

**Comment by nb9960** [comment]
Hey @Aadeesh11, Nice work! There is one more issue along with this, i.e., when one form is validated, the other also gets validated. Can you look into this as well, along with fixing the above issue?

**Comment by Aadeesh11** [comment]
> Hey @Aadeesh11, Nice work! There is one more issue along with this, i.e., when one form is validated, the other also gets validated. Can you look into this as well, along with fixing the above issue? https://user-images.githubusercontent.com/63557873/147666789-1f7ede9f-4ec4-47da-a5b1-f178cdf43fe3.mp4

Yes sure, thanks for the insights. Would look into the issue.

**Comment by ItsAdityaKSingh** [comment]
Hey, @nb9960 I am currently working on solving this issue #44

**Comment by nb9960** [comment]
> Hey, @nb9960 I am currently working on solving this issue #44

Have you started working on this?

**Comment by ItsAdityaKSingh** [comment]
Yup, I would like to solve this issue. If not solved then you may assign it to @Aadeesh11

**Comment by nb9960** [comment]
> Yup, I would like to solve this issue. If not solved then you may assign it to @Aadeesh11

Ok reopening that issue and assigning it to you then.

**Comment by nb9960** [comment]
> Yup, I would like to solve this issue. If not solved then you may assign it to @Aadeesh11

It seems as if @Aadeesh11 has some progress on this, so it would be better if you could look into some other issues.

**Comment by Aadeesh11** [comment]
> > Yup, I would like to solve this issue. If not solved then you may assign it to @Aadeesh11
> 
> It seems as if @Aadeesh11 has some progress on this, so it would be better if you could look into some other issues.

The issue has been fixed.

**Comment by ItsAdityaKSingh** [comment]
Uh oh! Sorry I too pushed the commits on pull request #45 @nb9960 :(

**Comment by nb9960** [comment]
Merged!! :tada:

**Pull request merged**
