### PR TITLE
Created CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
@nb9960 Minor documentation update to provide a standard Code of Conduct.

**Comment by cfsmp3** [comment]
I'm not sure I like this to be honest.

It lends itself to political discussions rather than technical ones.

We don't have anything like a behavior committee and I don't want to have one. I find they tend to be filled by people who care more about the politics than about the software.

So far we've all -I think- behaved correctly in the organization. We're small and we care about what we do, and anyone that doesn't treat everyone else with respect is going to be kicked out without a lot of back and forth.

**Comment by ItsAdityaKSingh** [comment]
Sure, that is true as per my understanding of this organization too. But I saw a few repositories in CCE itself having this file and thought about extending it to this for better documentation. Still, if it seems useless, I'm open to closing this as per your wish.

**Comment by tanisha083** [comment]
If there's no follow-up on this conversation, let's close this PR @ItsAdityaKSingh @cfsmp3

**Pull request closed without merging**
