### PR TITLE
Worked on issue #162 Automated the redundancy removal from email entered by the user

### PR DESCRIPTION
**Pull request by HarshitGulgulia**
Added trimRight() function

### CODE REVIEW

**Comment by ItsAdityaKSingh** [comment]
Your test cases are failing. Could you run `flutter format --set-exit-if-changed .` in your terminal for proper formatting of your changes :)

**Comment by HarshitGulgulia** [comment]
I have done the same. Please check.

**Comment by ItsAdityaKSingh** [comment]
Also, you could close PR #164 as it's the same.

**Comment by ItsAdityaKSingh** [comment]
@nb9960 You may review and merge this PR :)

**Pull request merged**
